title: Honey Traps Project
description: This site contains the documentation for the Honey Traps project offered by the WA Security Operations Center.
url: https://wagov.github.io/wasoc-honeytraps
layout: default
nav_enabled: true

search_enabled: true

search: 
  heading_level: 4
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
  focus_shortcut_key: 'k'

callouts_level: quiet # or loud
callouts:
  highlight:
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

remote_theme: just-the-docs/just-the-docs

footer_content: 'Acknowledgement of the Country: The Government of Western Australia acknowledges the traditional custodians throughout Western Australia and their continuing connection to the land, waters and community. We pay our respects to all members of the Aboriginal communities and their cultures; and to Elders both past and present.'